//DILARANG MEMPERJUAL BELI SC NYA! MAU REUPLOAD? TARO CREDIT GW ALDOUS FT VAN. EMANG ANJ LO JUAL SC GW MINIMAL BIKIN SC SENDIRI DECK😂 
#TANZA THE MAKERZ
#+6281293063326
#SC BOT V5
THANKS FOR MY SUBSCRIBER DONT FORGET TO SUBSCRIBE MY YOUTUBE CHANNEL ALDOUS FT VAN